export const UPDATE_NAVIGATION = 'SETTINGS/UPDATE_NAVIGATION'
export const SET_LANG = 'SETTINGS/LANG'
export const CHANGE_LANG = 'SETTINGS/CHANGE_LANG'
export const SET_STORAGE = 'SETTINGS/SET_STORAGE'